pimcore_data_hub:
    configurations:
        airports:
            general:
                active: true
                type: dataImporterDataObject
                name: airports
                description: 'airports data import'
                group: ''
                path: null
                modificationDate: 1699294398
                createDate: 1699287073
            loaderConfig:
                type: asset
                settings:
                    assetPath: /import/airports.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '1'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /airports
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                doDeltaCheck: true
                cleanup:
                    doCleanup: true
                    strategy: unpublish
            mappingConfig:
                -
                    label: 'id [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'ident [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ident
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'type [2]'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airport_type
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'name [3]'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'geopoint[4]'
                    dataSourceIndex:
                        - '4'
                        - '5'
                    transformationResultType: geoPoint
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: geographic_point
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: asGeopoint
                -
                    label: 'elevation_ft [6]'
                    dataSourceIndex:
                        - '6'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: elevation_ft
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'continent [7]'
                    dataSourceIndex:
                        - '7'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: continent
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'iso_country [8]'
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: iso_country
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'iso_region [9]'
                    dataSourceIndex:
                        - '9'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: iso_region
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'municipality [10]'
                    dataSourceIndex:
                        - '10'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: municipality
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'scheduled_service [11]'
                    dataSourceIndex:
                        - '11'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: scheduled_service
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'gps_code [12]'
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: gps_code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'iata_code [13]'
                    dataSourceIndex:
                        - '13'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: iata_code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'local_code [14]'
                    dataSourceIndex:
                        - '14'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: local_code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'home_link [15]'
                    dataSourceIndex:
                        - '15'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: home_link
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'wikipedia_link [16]'
                    dataSourceIndex:
                        - '16'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: wikipedia_link
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'keywords [17]'
                    dataSourceIndex:
                        - '17'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: keywords
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
